# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - r: 3.2
    - r: 3.3
    - r: 3.4
    - r: 3.5
    - r: 3.6
      after_success:
        - Rscript -e 'covr::codecov()'
    - r: devel
    - os: osx
      r: release

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

r_binary_packages:
  - covr
