# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - r: oldrel
    - r: release
      after_success:
        - Rscript -e 'covr::codecov()'
    - r: devel
    - os: osx
      r: release

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
